const CustomerData = [
    {
        orderNumber: '123',
        customerId: '456',
        customerName: 'Alice Johnson',
        customerNumber: '555-1234',
        orderTotal: 150.00,
        time: '12:00 PM',
        paymentMethod: 'Credit Card',
        date: '2024-08-01',
        items: [
            { name: 'Product 1', quantity: 2, price: 50.00 },
            { name: 'Product 2', quantity: 1, price: 50.00 },
        ],
    },
    {
        orderNumber: '124',
        customerId: '457',
        customerName: 'Bob Smith',
        customerNumber: '555-5678',
        orderTotal: 200.00,
        time: '1:00 PM',
        paymentMethod: 'PayPal',
        date: '2024-08-01',
        items: [
            { name: 'Product 3', quantity: 1, price: 100.00 },
            { name: 'Product 4', quantity: 2, price: 50.00 },
        ],
    },
    {
        orderNumber: '125',
        customerId: '458',
        customerName: 'Charlie Davis',
        customerNumber: '555-9012',
        orderTotal: 250.00,
        time: '2:00 PM',
        paymentMethod: 'Debit Card',
        date: '2024-02-08',
        items: [
            { name: 'Product 5', quantity: 5, price: 50.00 },
        ],
    },
    {
        orderNumber: '126',
        customerId: '459',
        customerName: 'Dana Lee',
        customerNumber: '555-3456',
        orderTotal: 300.00,
        time: '3:00 PM',
        paymentMethod: 'Cash',
        date: '2024-02-28',
        items: [
            { name: 'Product 6', quantity: 3, price: 100.00 },
        ],
    },
    {
        orderNumber: '127',
        customerId: '460',
        customerName: 'Evan Kim',
        customerNumber: '555-7890',
        orderTotal: 350.00,
        time: '4:00 PM',
        paymentMethod: 'Credit Card',
        date: '2024-08-03',
        items: [
            { name: 'Product 7', quantity: 2, price: 150.00 },
            { name: 'Product 8', quantity: 2, price: 25.00 },
        ],
    },
];
export default CustomerData;
